name: CI/CD Pipeline for giftproject

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Transfer project files to the server
        run: |
          rsync -av --delete --exclude='.git*' --exclude='.github' ./ -e "ssh -o StrictHostKeyChecking=no" ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/giftproject

      - name: Deploy to Docker Swarm
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
            cd /var/www/giftproject
            docker stack deploy --compose-file docker-compose.yml giftproject
          EOF
